#:schema node_modules/wrangler/config-schema.json
name = "embedding-worker"
main = "src/index.ts"
compatibility_date = "2024-08-21"

[vars]
# MY_VARIABLE = "production_value"

[triggers]
crons = ["* * * * *"]
