export const POSSIBLE_TOOLS = {
  // Slack
  SLACK_POST_MESSAGE: 'SLACK_POST_MESSAGE',
  SLACK_REACT: 'SLACK_REACT',

  // Repo interaction
  RI_LOAD_REPO: 'RI_LOAD_REPO',
  RI_CREATE_FILE: 'RI_CREATE_FILE',
  RI_MODIFY_FILE: 'RI_MODIFY_FILE',
  RI_RUN_PROJECT: 'RI_RUN_PROJECT',
  RI_RUN_COMMAND: 'RI_RUN_COMMAND',

  // "Local" git
  GIT_NEW_BRANCH: 'GIT_NEW_BRANCH',
  GIT_STAGE_AND_COMMIT: 'GIT_STAGE_AND_COMMIT',
  GIT_POST_PR: 'GIT_POST_PR',

  // Github
  GH_POST_PR_COMMENT: 'GH_POST_PR_COMMENT',
  GH_READ_PR_STATUS: 'GH_READ_PR_STATUS',

  // Tickets
  TICKET_POST_COMMENT: 'TICKET_POST_COMMENT',
}
